import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import clsx from "clsx";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={clsx(quicksand.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
